// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// double_me3
void double_me3(NumericVector x, NumericVector y);
RcppExport SEXP fret_double_me3(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    double_me3(x, y);
    return R_NilValue;
END_RCPP
}
// ksmooth_0_cpp
void ksmooth_0_cpp(NumericVector x, NumericVector y, double bandwidth, NumericVector xout, NumericVector yout);
RcppExport SEXP fret_ksmooth_0_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bandwidthSEXP, SEXP xoutSEXP, SEXP youtSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yout(youtSEXP);
    ksmooth_0_cpp(x, y, bandwidth, xout, yout);
    return R_NilValue;
END_RCPP
}
