// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ksmooth_0_cpp
NumericVector ksmooth_0_cpp(NumericVector x, NumericVector y, NumericVector xout, double bandwidth);
RcppExport SEXP fret_ksmooth_0_cpp(SEXP xSEXP, SEXP ySEXP, SEXP xoutSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(ksmooth_0_cpp(x, y, xout, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
