// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ksmooth_0_cpp
NumericVector ksmooth_0_cpp(NumericVector x, NumericVector y, NumericVector xout, double bandwidth);
RcppExport SEXP _fret_ksmooth_0_cpp(SEXP xSEXP, SEXP ySEXP, SEXP xoutSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(ksmooth_0_cpp(x, y, xout, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// ksmooth_0_stitch
NumericVector ksmooth_0_stitch(NumericVector x, NumericVector y, NumericVector xout, double bandwidth, double chunksize);
RcppExport SEXP _fret_ksmooth_0_stitch(SEXP xSEXP, SEXP ySEXP, SEXP xoutSEXP, SEXP bandwidthSEXP, SEXP chunksizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type chunksize(chunksizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ksmooth_0_stitch(x, y, xout, bandwidth, chunksize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fret_ksmooth_0_cpp", (DL_FUNC) &_fret_ksmooth_0_cpp, 4},
    {"_fret_ksmooth_0_stitch", (DL_FUNC) &_fret_ksmooth_0_stitch, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fret(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
