# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Kernel smoother for integer locations
#' @description Assumes missing locations have observation of 0
#' @param x Input locations (integers), sorted
#' @param y Input observations, should be length of x and non-missing
#' @param xout Output locations
#' @param bandwidth Bandwidth. Should be an odd integer
ksmooth_0_cpp <- function(x, y, xout, bandwidth) {
    .Call('_fret_ksmooth_0_cpp', PACKAGE = 'fret', x, y, xout, bandwidth)
}

#' @title Kernel smoother for integer locations
#' @description Assumes missing locations have observation of 0
#' @param x Input locations (integers), sorted
#' @param y Input observations, should be length of x and non-missing
#' @param xout Output locations
#' @param bandwidth Bandwidth. Should be an odd integer
#' @param chunksize Chunksize to work in
#' @export
ksmooth_0_stitch <- function(x, y, xout, bandwidth, chunksize) {
    .Call('_fret_ksmooth_0_stitch', PACKAGE = 'fret', x, y, xout, bandwidth, chunksize)
}

