# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ksmooth_0_cpp <- function(x, y, xout, bandwidth) {
    .Call('fret_ksmooth_0_cpp', PACKAGE = 'fret', x, y, xout, bandwidth)
}

