# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

double_me3 <- function(x) {
    .Call('fret_double_me3', PACKAGE = 'fret', x)
}

ksmooth_0_cpp <- function(x, y, bandwidth, xout) {
    .Call('fret_ksmooth_0_cpp', PACKAGE = 'fret', x, y, bandwidth, xout)
}

